### ISSUE TITLE
Extra HAL to a separate repository

### ISSUE THREAD

**Issue by BlueAndi** [BlueAndi/RadonUlzer#119]
The idea is to separate the HAL for the target, simulation and its interfaces in github repositories.
The advantage is to use them in different other projects too, different than RadonUlzer.

Proposal:
* ZumoHALATmega32u4: https://github.com/BlueAndi/ZumoHALATmega32u4
* ZumoHALWebots: https://github.com/BlueAndi/ZumoHALWebots
* ZumoHALInterfaces: https://github.com/BlueAndi/ZumoHALInterfaces

**Comment by BlueAndi** [comment]
@eble108 This would be an advantage on your side as well, right?

**Comment by BlueAndi** [comment]
Branch with extracted HALs: https://github.com/BlueAndi/RadonUlzer/tree/extractHALs

**Comment by gabryelreyes** [comment]
Closed by #122
