### ISSUE TITLE
Update Webots to R2023b

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/RadonUlzer#16]
New version allows for use of Launcher Script for external controllers.

May bring breaking changes to the world and PROTOs

**Comment by BlueAndi** [comment]
https://github.com/cyberbotics/webots/pull/5629

**Comment by gabryelreyes** [comment]
Yes! That is actually my main reason for the upgrade :D

**Comment by gabryelreyes** [comment]
PROTOS succesfully updated: Changed Transform to Pose without major trouble.

Current problem: Applications (currently using LineFollower) don't do anything in the simulation.

Following observations made:
- Program and Simulation run. Sim time is running and messages printed to console.
- robot-display does not show anything
- Button A press is working. Program goes into MotorSpeedCalibrationState
- Robot does not move
- From MotorSpeedCalibrationState goes into ErrorState with error message MS=0 (from  `MotorSpeedCalibrationState ::finishCalibration()` )
- Pressing Button A to re-run motor calibration gets the same result.

Problem-solving:
- Seems like the interfaces between Webots' devices and external controllers are not working properly.
- Did the initialization change?
- Note that all used devices are found at the start of the program, and no further warnings are issued.
- Compilation process does not issue any warnings.
- Program runs as expected when reverting to R2023a

**Comment by BlueAndi** [comment]
I checked the main branch and its working with 2023b.

**Comment by BlueAndi** [comment]
@gabryelreyes Could it be, that you are using the lib/webots from the previous version? Remove it and compile again, it will automatically create the lib.

**Comment by gabryelreyes** [comment]
Yes, that fixed it. Thanks! 😁

**Comment by BlueAndi** [comment]
Is it possible that in case of a "clean all" we remove lib/webots too?

**Comment by gabryelreyes** [comment]
Hooks does not seem to work on "clean" target (https://github.com/platformio/platformio-core/issues/4456)
Is it possible to copy the library to the .pio/build folder, instead of lib ? In that way, "clean all" would definitely remove the files

**Comment by BlueAndi** [comment]
You can copy it to .pio/build, but it won't be build. :-)
Let's track the pio ticket and if they provide this feature, we will implement it.

**Comment by gabryelreyes** [comment]
According to 6f9fe7e, R2023a is still supported. This is only possible if 6450858 is reverted, or it should not be merged into the main branch until the backwards compatibility is no longer supported.

**Comment by BlueAndi** [comment]
Is there any advantage for introducing POSE, instead of TRANSFORM?

**Comment by gabryelreyes** [comment]
Not really. The TRANSFORM gets converted to POSE every time the simulation is opened, but other than, that it is fully compatible with both versions.

**Comment by BlueAndi** [comment]
Webots R2023b already supported.
