### ISSUE TITLE
Odometry random incrementation.

### ISSUE THREAD

**Issue by paulgrammy** [BlueAndi/RadonUlzer#38]
After running some basic tests I've encountered an issue when calling odometry for longer periods of time.

The test involved the robot endlessly running through the course while periodically outputting X and Y coordinates. It has been done in order to map out  key points/areas of the original track for other implementations:
![grafik](https://github.com/BlueAndi/RadonUlzer/assets/145540009/6b8fa2ad-de6b-40f5-91d3-cdec514e27c8)

The following values have been found with AND without clearing position after crossing the start/end line:
![grafik](https://github.com/BlueAndi/RadonUlzer/assets/145540009/942d2591-5ca0-46fa-9a92-9eed2cb03f95)

Conclusions:
- Y values are somewhat consistent while X isn't at all
- clearing position at the start/end line helps

**Comment by BlueAndi** [comment]
main branch is updated, please verify.

**Comment by paulgrammy** [comment]
After testing, I now get consistent results until around the 46 second simulation timestamp (or middle of 3rd lap)

![grafik](https://github.com/BlueAndi/RadonUlzer/assets/145540009/c1982e4f-fc18-40dd-b568-7b101fc29690)

tests were done one default track and different parameter sets, the first one giving the best results.

It looks like the PID Controller exponentially adds up the differences and somewhere at that timestamp, they start increasing very fast: when the robot is running on a straight segment, neither of the axes are constant, meaning that the input values of the PID are being heavily and drastically modified to fix the measured mistake.

This could also be why the first parameter set works the best, because it is slower and more precise.  The other sets blow up the calculations even more

**Comment by BlueAndi** [comment]
There will be always a small error which sums up over time. Usually there are known fix waypoints, where this needs to be compensated again. This can not be handled by RU and must be handled on higher level like DCS.

**Comment by paulgrammy** [comment]
Resetting orientation to Pi/2 and clearing the PID controller on Start/Endline recognition seems to fix the issue.
