### ISSUE TITLE
New supervisor requires python and numpy. Extend documentation.

### ISSUE THREAD

**Issue by LuDubies** [BlueAndi/RadonUlzer#49]
OR make optional/turn off by default??

**Comment by LuDubies** [comment]
a7d04fce47ebb01fee4f8575b6119662e487a5b9 introduced the Supervisor into the LineFollowerTrack world.
This supervisor has numpy requirements, These are not currently mentioned in the docu.

Options are:
 - split into unsupervised and supervised world
 - extend requirements in documentation
 - make supervisor optional some other way

**Comment by gabryelreyes** [comment]
Closed with #50
