### ISSUE TITLE
Update the linear motor max. velocity in simulation

### ISSUE THREAD

**Issue by BlueAndi** [BlueAndi/RadonUlzer#84]
Goal: The max. motor speed in steps/s shall be equal between simulation and target. Because the encoder steps / mm are known, the max. velocity can be calculated.

**Comment by BlueAndi** [comment]
| Robot | max. motor speed [steps/s] | max. motor speed [m/s] |
| - | - | - |
| 1 | 3800 | 0.475 |

**Comment by gabryelreyes** [comment]
Closed in b3a3d53f7c42664170bbe8e87d46c1dab5e0244e
